version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOSTNAME=iris
      - DB_USERNAME=demo
      - DB_PASSWORD=demo
      - DB_PORT=1972
      - DB_NAMESPACE=USER
    env_file:
      - .env
    depends_on:
      - iris

  iris:
    image: intersystemsdc/iris-community:latest
    container_name: iris-comm
    environment:
      - IRIS_PASSWORD=demo
      - IRIS_USERNAME=demo
    ports:
      - "1972:1972"
      - "52773:52773"
    restart: unless-stopped
    volumes:
      - iris-data:/data

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    restart: unless-stopped

volumes:
  iris-data: 
